# Generated by Django 4.0 on 2023-11-27 10:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('companyAddress', models.CharField(max_length=255)),
                ('companyEmail', models.CharField(max_length=255)),
                ('contactNumber', models.CharField(max_length=20)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'Admin'), ('JS', 'Job Seeker'), ('JP', 'Job Provider')], max_length=2)),
                ('fName', models.CharField(max_length=255)),
                ('lName', models.CharField(max_length=255)),
                ('mName', models.CharField(max_length=255, null=True)),
                ('emailAddress', models.CharField(max_length=255)),
                ('contactNo', models.CharField(max_length=13)),
                ('civilStatus', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthDate', models.DateField(verbose_name='date_born')),
                ('houseNo', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('province', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=255)),
                ('jobDescription', models.TextField()),
                ('jobRequirements', models.CharField(blank=True, max_length=255, null=True)),
                ('jobLocation', models.CharField(max_length=255)),
                ('salaryRange', models.CharField(blank=True, max_length=255, null=True)),
                ('deadLine', models.DateField(verbose_name='application_deadline')),
                ('companyID', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='GigHub.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='application_date')),
                ('applicationStatus', models.CharField(choices=[('applied', 'Applied'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('hired', 'Hired')], max_length=30)),
                ('applicantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GigHub.user')),
                ('jobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GigHub.jobpostings')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='employerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GigHub.user'),
        ),
    ]
