# Generated by Django 4.0 on 2023-11-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employerID',
            field=models.ForeignKey(limit_choices_to={'role': 'JP'}, on_delete=django.db.models.deletion.CASCADE, to='GigHub.user'),
        ),
    ]
