# Generated by Django 4.0 on 2023-11-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0002_alter_company_employerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='placeholder.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='GigHub2023', max_length=255),
        ),
    ]
