# Generated by Django 4.2.7 on 2023-11-30 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0004_remove_user_emailaddress_user_email_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='placeholder.png', upload_to='')),
                ('role', models.CharField(choices=[('A', 'Admin'), ('JS', 'Job Seeker'), ('JP', 'Job Provider')], max_length=2)),
                ('fName', models.CharField(max_length=255)),
                ('lName', models.CharField(max_length=255)),
                ('mName', models.CharField(max_length=255, null=True)),
                ('contactNo', models.CharField(max_length=13)),
                ('civilStatus', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthDate', models.DateField(verbose_name='date_born')),
                ('houseNo', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('province', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='employerID',
            field=models.ForeignKey(limit_choices_to={'role': 'JP'}, on_delete=django.db.models.deletion.CASCADE, to='GigHub.profile'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applicantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GigHub.profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
