# Generated by Django 4.2.7 on 2023-11-30 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GigHub', '0005_profile_alter_company_employerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
