# Generated by Django 4.2.7 on 2023-11-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0006_profile_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/placeholder.png', upload_to='profiles/'),
        ),
    ]
