# Generated by Django 4.2.7 on 2023-11-30 07:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GigHub', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwordOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActivated', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 11, 30, 15, 1, 21, 359720))),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
