# Generated by Django 4.2.7 on 2023-12-02 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0008_passwordotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 8, 37, 15, 64565)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='civilStatus',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced')], max_length=20),
        ),
    ]
