# Generated by Django 4.2.7 on 2023-12-02 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0009_alter_passwordotp_date_alter_profile_civilstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobpostings',
            name='jobRequirements',
        ),
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 8, 44, 59, 165709)),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='GigHub.skills'),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='jobRequirements',
            field=models.ManyToManyField(to='GigHub.skills'),
        ),
    ]
