# Generated by Django 4.2.7 on 2023-12-02 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0010_skills_remove_jobpostings_jobrequirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 10, 27, 43, 699813)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthDate',
            field=models.DateField(null=True, verbose_name='date_born'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='civilStatus',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
