# Generated by Django 4.2.7 on 2023-12-02 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0011_alter_passwordotp_date_alter_profile_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 11, 21, 12, 517050)),
        ),
    ]
