# Generated by Django 4.2.7 on 2023-12-02 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0012_profile_is_verified_alter_passwordotp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 12, 28, 29, 368494)),
        ),
    ]
