# Generated by Django 4.2.7 on 2023-12-02 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0013_alter_passwordotp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='baranggay',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 13, 21, 49, 37608)),
        ),
    ]
