# Generated by Django 4.2.7 on 2023-12-02 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0014_profile_baranggay_alter_passwordotp_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 13, 49, 56, 119415)),
        ),
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GigHub.degrees')),
            ],
        ),
        migrations.CreateModel(
            name='collegeTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearGraduated', models.CharField(max_length=5)),
                ('degree', models.ManyToManyField(to='GigHub.degrees')),
                ('institution', models.ManyToManyField(to='GigHub.institution')),
                ('major', models.ManyToManyField(to='GigHub.majors')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GigHub.profile')),
            ],
        ),
    ]
