# Generated by Django 4.2.7 on 2023-12-03 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0015_degrees_institution_alter_passwordotp_date_majors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='verificationLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collegetaken',
            name='major',
            field=models.ManyToManyField(blank=True, to='GigHub.majors'),
        ),
        migrations.AlterField(
            model_name='collegetaken',
            name='yearGraduated',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applicationStatus',
            field=models.CharField(choices=[('applied', 'Applied'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='Applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 13, 15, 8, 914475)),
        ),
    ]
