# Generated by Django 4.2.7 on 2023-12-03 06:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0016_remove_profile_is_verified_profile_verificationlevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='companyAddress',
        ),
        migrations.RemoveField(
            model_name='company',
            name='companyEmail',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contactNumber',
        ),
        migrations.AddField(
            model_name='company',
            name='baranggay',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='bldgNo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='empRange',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='strt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 14, 6, 35, 138503)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='civilStatus',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('SE', 'Separated')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GigHub.industry'),
        ),
    ]
