# Generated by Django 4.2.7 on 2023-12-05 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0017_industry_remove_company_companyaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 16, 5, 44, 383813)),
        ),
    ]
