# Generated by Django 4.2.7 on 2023-12-05 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0018_profile_suffix_alter_passwordotp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegetaken',
            name='award',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 17, 44, 4, 938025)),
        ),
    ]
