# Generated by Django 4.2.7 on 2023-12-06 05:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0019_collegetaken_award_alter_passwordotp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 13, 24, 14, 234394)),
        ),
        migrations.CreateModel(
            name='companyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GigHub.company')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GigHub.profile')),
            ],
        ),
    ]
