# Generated by Django 4.2.7 on 2023-12-06 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0020_alter_passwordotp_date_companystaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employerID',
        ),
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 14, 19, 43, 71629)),
        ),
        migrations.AddField(
            model_name='company',
            name='employerID',
            field=models.ManyToManyField(to='GigHub.profile'),
        ),
    ]
