# Generated by Django 4.2.7 on 2023-12-07 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0021_remove_company_employerid_alter_passwordotp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='scope',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='timeline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 16, 33, 46, 702378)),
        ),
    ]
