# Generated by Django 4.2.7 on 2023-12-09 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0023_alter_passwordotp_date_certificates_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostings',
            name='deadLine',
        ),
        migrations.RemoveField(
            model_name='jobpostings',
            name='jobLocation',
        ),
        migrations.RemoveField(
            model_name='jobpostings',
            name='salaryRange',
        ),
        migrations.AddField(
            model_name='jobpostings',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 9), verbose_name='application_date'),
        ),
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 11, 31, 32, 221445)),
        ),
    ]
