# Generated by Django 4.2.7 on 2023-12-09 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0024_remove_jobpostings_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostings',
            name='deadLine',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 14, 28, 52, 102624)),
        ),
    ]
