# Generated by Django 4.2.7 on 2023-12-11 01:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GigHub', '0027_alter_jobapplication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 1, 45, 16, 61979, tzinfo=datetime.timezone.utc), verbose_name='application_date'),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 1, 45, 16, 60973, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='passwordotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 9, 45, 16, 62964)),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobApp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GigHub.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageContent', models.CharField(max_length=255)),
                ('senderRole', models.CharField(max_length=50)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GigHub.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GigHub.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('dateandtime', models.DateTimeField(auto_now_add=True)),
                ('viewer', models.ManyToManyField(to='GigHub.profile')),
            ],
        ),
    ]
